### ISSUE TITLE
define query string parameters for pagination

### ISSUE THREAD

**Issue by torgo** [openregister/specification#7]

**Comment by philandstuff** [comment]
see also alphagov/tech-and-data-standards#4 which is related.  One thing I have learned from that issue is that whatever way we handle pagination, we should try to identify resources which don't change.  The current `page-index` and `page-size` parameters result in resources which _do_ change as more entries are added to a register.

**Comment by philandstuff** [comment]
Do we actually need to define the parameters in the spec? If clients are rightly following `previous` and `next` link headers, can the spec simply treat pagination query strings as opaque?

**Comment by arnau** [comment]
Agreed that the spec defines pagination as implementation specific so relies on the `Link` header for rels `next` and `previous`.
